config/routes.rb
MyBlog::Application.routes.draw do
  get "posts/new"

  get "blogs/index"

  get "home/index"
  
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}
  
  match 'blog/:username' => 'blogs#show', :as => :user_blog

  match 'aboutus' => 'home#about'
  
  match 'contactus' => 'home#contact'
  match 'post_save' => 'posts#create', :as => :post_save
  match 'post/:id/update' => 'posts#update', :as => :update_post
  match 'post/:id/delete' => 'posts#destroy', :as => :delete_post, :via => :delete
  match 'post/:id/comment' => 'posts#comment', :as => :post_comments

  match '/' => 'blogs#show', :constraints => { :subdomain => /.+/ }
  root :to => 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :posts
  attr_accessible :subdomain
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :blog
  attr_accessible :content, :email, :name, :blog_id, :post_id
  validates_presence_of :content, :email, :name, :blog_id, :post_id
  validates :email, :format => {:with => Devise.email_regexp}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
  has_many :comments
  
  attr_accessible :content, :title, :tag_list, :blog_id

  validates_presence_of :content, :title

  acts_as_taggable

  def comment?
    return !self.comments.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_one :blog
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :user_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  validates_presence_of :user_name

  def subdomain
    self.blog.try(:subdomain)
  end

  def edit_post?(post)
    self.blog.posts.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery

  def after_sign_in_path_for(resource)

  
    if current_user.subdomain.blank?    
      current_user.build_blog({subdomain: 'narutosanjiv'}).save
    end
    user_blog_path(username: current_user.subdomain)
  end

  
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController 
  before_filter :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  
  end

  def show
    @blog = Blog.find_by_subdomain(params[:username])
  end
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  def index
    if current_user
      redirect_to user_blog_path(:username => current_user.subdomain)  
    end
  end

  def about

  end

  def contact 

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:new, :create, :update, :destroy]
  respond_to :html, :json
  def new
    @post = Post.new 
  end

  def create
    puts "Parameter passed in #{params }" 
    @post =Post.new(params[:post])
    respond_to do|format|
      if @post.save
        format.html{redirect_to root_url and return } 
      else
        format.html{render 'posts/new'}
      end
    end
  end

  def edit 

  end

  def update
    @post = Post.find(params[:id])
    respond_to do|format|
      if @post.update_attributes(params[:post])
        format.html{redirect_to(@post, :notice => 'Post updated successfully')}
        format.json { respond_with_bip(@post) }
      else
        format.html {render 'post/new' }
        format.json{ respond_with @post }

      end
    end
  end
  
  def destroy 
    @post = Post.find(params[:id])
    @post_id = @post.id
    respond_to do|format|
      if @post.destroy
        format.js{render 'posts/destroy'}
      end
    end
  end

  def comment
    @post = Post.find(params[:id])
    @new_comment = Comment.new
    @comments = @post.comments.order('created_at desc')
    if request.post?
      
      respond_to do|format|
        @comment_to_save = Comment.new(params[:comment])
        @comment_to_save.post_id = @post.id
        @comment_to_save.blog_id = @post.blog.id
        if @comment_to_save.save
          @post = @post.reload
          @comments = @post.comments.order('created_at desc')
          format.js
        else
          format.js{ render 'error' }   
        end
      end
    end

  end

  def load_more_comment

  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # GET /resource/sign_up
  def new
    resource = build_resource({})
    respond_with resource
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController 
  def new 

  end

  def create
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource 
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping = Devise.mappings[:user]
  end
  
  def current_blog(user)
    user.blog  
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/index.html.haml
%h1 Blogs#index
%p Find me in app/views/blogs/index.html.haml

app/views/blogs/show.html.haml
= stylesheet_link_tag "posts"
.new_post_btn
  %a{:class => 'btn btn-primary', :href => posts_new_path} New Path
.center-column
  #header
    .blog-name
      %a{:href => '#'}= @blog.user.user_name
    .description
      Just Another Blogsite
    = render :partial => 'shared/blogs/post_view', :collection => @blog.posts.order('updated_at desc'), :as => :post


:javascript
  $(document).ready(function(){
    jQuery(".best_in_place").best_in_place();
  });

app/views/home/about.html.haml
%p
  This is free Blogging Site Inspired by Wordpress
  It is requested from user to post any material which is against the law of particular nation or region. Those who will be found broken the local law will be blocked in near future.

%p 
  Tell Other your friend about this new blogging site

%p
  All Indian Law applicable to this site.

app/views/home/contact.html.haml
%p 
 You can me contact me through email at narutosanjiv@gmail.com
 Or you can follow me at twitter 
 My Blog is at narutosanjiv.wordpress.com

app/views/home/index.html.haml
%h1
  My Blog: Create and Publish Your content free
%h3.margin_bottom
  Share what you want, with whom you want.
.row
  .span4
    %h2 
      Welcome!
      %p
        This My Blog is free WebBlog Designed by Sanjiv Kumar Jha. Any one free to clone to git hub and modify it according to its requirement.
      %p
        If you have any suggestions or questions
        %a{:href => "mailto:narutosanjiv@gmail.com"} Reach at me.
    
  .span4.offset1 
    = link_to "New User! Register", new_user_registration_path, :class => 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    :css
      body{
        padding-top: 60px;
      }
    %title MyBlog
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "layout", "login_form", "message"
    = yield :css
    = javascript_include_tag "application"
    = yield :js
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_url} My Blog
          .nav-collapse
            %ul.nav
              %li.active
                %a{:href => root_url} Home
              %li
                %a{:href => "/aboutus"} About
              %li
                %a{:href => '/contactus'} Contact
              - if current_user
                %li
                  %a{:href => posts_new_path} New Post
            %form.navbar-search.pull-left
              %input.search-query.span2{:type => 'text', :placeholder => 'Search Post '}
          .btn-group.pull-right
            - if current_user.blank?
              %ul#landing_nav
                %li
                  %a.login{:href => '#'} Log in
            - else
              %a.btn.dropdown-toggle{"data-toggle" => 'dropdown', :href => '#'}
                #{current_user.email}
                %i.icon-user
                %span.caret
              %ul.dropdown-menu
                %li
                  %a{:href => '#'} Profile
                %li.divider
                %li
                  %a{:href => destroy_user_session_path, :data => {:method => :delete} } Sign Out
    .container
      = render 'shared/login_form', :resource => resource
      = yield

:javascript
  $(document).keydown(function(e) {
    if (e.keyCode == 27) 
    {
      $('#root-signin-popup').hide();
    }
  });
  $(document).ready(function(){
    $('.login').click(function(){
      $('#root-signin-popup').toggle();
    })
  });

app/views/posts/_comment.html.haml
-name = comment.name
-created_at = comment.created_at
-content = comment.content
%tr.cmtBox
  %td
    %p.name
      #{name}
    %p.created_at
      #{created_at.to_date.to_formatted_s}
  %td.post_comment
    .comment
      #{content}

app/views/posts/_new_comment.html.haml
= form_for(new_comment, :url => post_comments_path(:id => post.id), :html => {:remote => true, :class => 'form-horizontal', :id => 'new_comment_form'}) do|f|
  = f.hidden_field :post_id, :value => post.id
  = f.hidden_field :blog_id, :value => post.blog.id
  .row
    = f.label :name
  .row
    = f.text_field :name
  .row
    = f.label :email
  .row
    = f.text_field :email
  .row
    = f.label :comment
  .row
    = f.text_area :content, :rows => '10', :cols => '20'
  .row
    = f.submit :save, :value => 'Save', :class => 'btn btn-primary', :style => 'margin-top:10px;'

app/views/posts/comment.html.haml
= stylesheet_link_tag "comment"
.content
  .title
    %h1= @post.title
  .description
    = @post.content

#post_comment
  %p{:style => "clear: left;padding-left: 10px; padding-top:5px;"}
    = link_to "Write Comment Here(#{@post.comments.count})", "#", :class => "new_comment_link", :style => "font-size:15px;"
  #new_comment
    = render :partial => 'new_comment', :locals => {:post => @post, :new_comment => @new_comment}  
  = render :partial => 'shared/posts/comments', :locals => {:comments => @comments, :post => @post}

app/views/posts/comment.js.haml
$('.post_comments_box').remove();
$('#comment_name').val('');
$('#comment_email').val('');
$('#comment_content').val('');
$('#error_explanation').remove();
$('.comments_count').remove();
$('.new_comment_link').html("Write Comment Here(#{@comments.count})");
$('#new_comment').after("#{escape_javascript(render :partial => 'shared/posts/comments', :locals => {:comments => @comments, :post => @post})}");

app/views/posts/create.html.haml
%h1 Posts#create
%p Find me in app/views/posts/create.html.haml

app/views/posts/destroy.js.haml
$("#post-#{escape_javascript(@post_id.to_s)}.hentry").parent().remove();

app/views/posts/error.js.haml
$('#error_explanation').remove();
$('#new_comment_form').prepend("#{escape_javascript(render "shared/error_messages", :error_resource => @comment_to_save)}");

app/views/posts/new.html.haml
%h1 Write a New Post
%p New Post
= form_for(@post, :url => post_save_path, :html => {:class => "form-horizontal"}) do|f|
  = render 'shared/error_messages', :error_resource => @post
  = f.hidden_field :blog_id, :value => current_user.blog.id
  = f.label :title
  = f.text_area :title, :rows => 2, :cols => 10, :placeholder => "Title"
  = f.label :content
  = f.text_area :content, :rows=> 5, :cols => 20, :placeholder => "Content"
  = f.label :Add_Tag
  = f.text_field :tag_list, :placeholder => 'Comma Separated tag'
  = f.submit :Save, :class => 'btn btn-primary'

:javascript
  $(document).ready(function(){
    $('#post_content').wysihtml5();
  });

app/views/shared/_error_messages.html.haml
- if error_resource && error_resource.errors.any?
  #error_explanation.validation_msg.error_msg
    %h2
      = pluralize(error_resource.errors.count, "error")
      prohibited this post from being saved:
    %ul
      - error_resource.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_login.html.haml
= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => "signin-form", :id => "oauth_user_new"}) do |f|
  = hidden_field_tag(:from, controller_name)
  = hidden_field_tag(:action_type, 'sign_in')
  = render 'shared/error_messages', :error_resource => resource
  = f.email_field :email, class: "login_fields", placeholder: "Email Id", style: "border: 1px solid #888;border-radius: 0px;padding-left:10px;"
  %br
  %br
  = f.password_field :password, class: "login_fields", placeholder: "Password", style: "border: 1px solid #888;border-radius: 0px;margin-right: 4px;padding-left:10px;"

  - if devise_mapping.recoverable? && controller_name != 'passwords'
    .forgot-password
      = link_to "Forgot your password?", new_password_path(resource_name)
  
  = f.submit "Sign in", class: "btn_orig"

app/views/shared/_login_form.html.haml
- content_for :css do
  = stylesheet_link_tag "login_form"
#root-signin-popup{:style => 'display:none'}
  .root_signin_wraper
    .sign_in_new_root
      .sign_in_details
        = render 'shared/login', :resource => resource           

app/views/shared/blogs/_post_view.html.haml
.content
  %div{:class => "status-publish format-standard hentry", :id => "post-#{post.id}"}
    .post-info
      %h1
        = link_to post.title, post_comments_path(:id => post.id) 
      .timestamp 
        = post.updated_at.strftime('%Y-%m-%d')
      .comment-bubble
        %a{:href => "/post/#{post.id}/comment/#new_comment"}= post.comments.try(:count) 
      .clearboth
    - if current_user && current_user.edit_post?(post)
      .closebutton
        %a{:href => '#', :data => {:remote => "true", :method => :delete}, :href => delete_post_path(:id => post.id)}
    .post-content
      = best_in_place_if current_user && current_user.edit_post?(post), post, :content, :type => :textarea, :path => update_post_path(:id => post.id), :display_with => lambda { |v| v.html_safe }
      .sharedaddy.sd-like-enabled.sd-sharing-enabled
    .clearboth
    .post-meta-data
      "Tags"
      %span
        = post.tag_list
    

app/views/shared/posts/_comments.html.haml
- if post.comments.present?
  .comments_count
    Total Comments:Showing 1 - #{post.comments.count} Comments
  .grid_12.post_comments_box
    %table{:style => "margin-bottom:20px;"}
      %tbody.comment_box
        = render :partial => 'posts/comment', :collection => comments, :as => :comment
      %tfoot
-else
  No Comment on this post yet